[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
bullet_core = { workspace = true }
shared_backend = { path = "shared", package = "shared_backend"}
