[package]
name = "bullet_cuda_backend"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
bullet_core = { workspace = true, features = ["cuda"] }
cudarc = { workspace = true }

[features]
cudnn = []
