on:
    pull_request:
    push:
      branches:
        - main

name: cargo
jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: clippy
        - run: CUDA_PATH=. HIP_PATH=. cargo clippy --workspace --all-targets --features=cuda,rocm -- --deny warnings

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - run: cargo test --workspace

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
          with:
            components: rustfmt
        - run: cargo fmt --all -- --check

